# search in chatgpt as "give me one kubernetes network policy yaml based on the pod label,mysql should accept connection from backend pod" 
# mysql accepting traffic only from the backend 
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: mysql-allow-backend
  namespace: expense  # Change to your namespace
spec:
  podSelector:
    matchLabels: # copy the tags from the k8-expense --> mysql --> manifest.yaml
      app: mysql
      tier: mysql
      project: expense
  policyTypes:
    - Ingress
  ingress:
    - from:
        - podSelector:
            matchLabels: # copy the tags from the k8-expense --> backend --> manifest.yaml
              app: backend
              tier: backend
              project: expense
      ports:
        - protocol: TCP
          port: 3306
